<header>
  <div class="header-container">
    <div class="company-name"><a href="index.php">LifeReady</a></div>
    <div class="company-slogan"><p>Preparing the next generation.</p></div>
    <?php include 'nav.inc'; ?>
    <div class="auth-buttons">
      <a href="register.php" class="btn-header btn-register">Register</a>
      <a href="login.php" class="btn-header btn-login">Login</a>
    </div>
  </div>
</header>